name: React CI + Deploy

on:
  push:
    branches: ["production"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Run lint
        run: pnpm lint

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }} 
          port: ${{ secrets.SFTP_PORT }} 
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          local_path: "dist/*"
          remote_path: "/home/u325699793/domains/lascasasgaming.com/public_html/test-deploy"
          sftp_only: true