name: React CI + Deploy

on:
  push:
    branches: ["production"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Run lint
        run: pnpm lint

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }} # your FTP host
          username: ${{ secrets.FTP_USER }} # FTP username
          password: ${{ secrets.FTP_PASS }} # FTP password
          port: ${{ secrets.FTP_PORT }} # usually 21
          protocol: ftp # use ftp or ftps
          local-dir: dist # folder to upload
          server-dir: /public_html/test-deploy # destination folder on server
          passive: true # enable passive mode
